### ISSUE TITLE
Cleanup Segment_mini

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN-trait-segmentation#4]
Cleanup some stray files and out of date README content for the Segment_mini directory
- Remove Docker_SMP_env_v2 and Singularity_def subdirectories (assuming they are no longer necessary)
- Remove load_model_instruction.txt - move the content into the README
- Update `Create the singularity image` README section to use the `ghcr.io/hdr-bgnn/bgnn-trait-segmentation` instead. https://github.com/hdr-bgnn/BGNN-trait-segmentation/blob/ccecb649a40968acd29efa62718ee6021fbce5ae/Segment_mini/README.md?plain=1#L96
- Fill in contact information in README - The README has a place for contact email for Maruf but no email: https://github.com/hdr-bgnn/BGNN-trait-segmentation/blob/ccecb649a40968acd29efa62718ee6021fbce5ae/Segment_mini/README.md?plain=1#L3
-

**Comment by thibaulttabarin** [comment]
Close #8
