### ISSUE TITLE
Reduce code duplication

### ISSUE THREAD

**Issue by johnbradley** [hdr-bgnn/BGNN-trait-segmentation#5]
Remove duplicated code in **segmentation_main.p**y and **helper.py**.

There are two slightly different copies of **segmentation_main.py** in this repo:
- https://github.com/hdr-bgnn/BGNN-trait-segmentation/blob/main/Segment_mini/scripts/segmentation_main.py
- https://github.com/hdr-bgnn/BGNN-trait-segmentation/blob/main/pipeline/segmentation_main.py

There are also two copies of **helper.py** (**helper_mini.py**).
- https://github.com/hdr-bgnn/BGNN-trait-segmentation/blob/main/pipeline/scripts/helper.py
- https://github.com/hdr-bgnn/BGNN-trait-segmentation/blob/main/Segment_mini/scripts/helper_mini.py

See if we can extract out the common parts to a central location.

**Comment by thibaulttabarin** [comment]
I remove the folder pipeline\ that we used for development. At this point, the folder seems irrelevant to me.
This deletion resolves all the conflict mentioned
Thanks for pointing this out.
Close #5
