### ISSUE TITLE
realease doesn't take the path /pipeline/  when using singularity

### ISSUE THREAD

**Issue by thibaulttabarin** [hdr-bgnn/BGNN-trait-segmentation#9]
For the deployment part, the docker file https://github.com/hdr-bgnn/BGNN-trait-segmentation/blob/main/Segment_mini/Dockerfile contained a fix to have /pipeline/ in the PATH  in order to call the segmentation_main.py directly wihtout using python /pipeline/segmentation_mian.py <input> <ouput>. (if I understand correctly) 
When I import the container in singularity format with: singularity pull trait-seg.sif docker://ghcr.io.....
the container works using python /pipeline/segmentation_main.py <input> <ouput>.
It seems during the conversion something went wrong. 
The problem is that the snakefiles have been built using segmentation_main.py <input> <ouput>. I am currently changing them to python /pipeline/segmentation_main.py <input> <ouput>.
But I find this behaviour weird.

**Comment by johnbradley** [comment]
I think this is a problem because segmentation_main.py doesn't have execute permissions.
```
$ docker run -it ghcr.io/hdr-bgnn/bgnn-trait-segmentation:latest ls -l /pipeline/segmentation_main.py
-rw-r--r-- 1 root root 3230 May 27 22:20 /pipeline/segmentation_main.py
```
I will create a PR to address this.

**Comment by thibaulttabarin** [comment]
I will check that later, but yes, it does make sense. Thanks for catching this up, I should have been able to do it myself, but I didn't

**Comment by thibaulttabarin** [comment]
Ok I see, but where did you run : chmod a+x segmentation_main.py ?

**Comment by johnbradley** [comment]
> Ok I see, but where did you run : chmod a+x segmentation_main.py ?

I ran this command within the pipeline directory of a clone of this repo.
git tracks file permissions in addition to file contents.
So when I ran chmod the file became modified.
Then I ran `git add segmentation_main.py` then `git commit ...` then `git push ...`.
Does this make sense?
